### ISSUE TITLE
小人的特質介紹跑版

### ISSUE THREAD

**Issue by kusolibra** [miZyind/ONI-Mods#1]
開新圖選三個小人時，其特質介紹跑版。尚不確定遊戲中會不會有同樣狀況。

![image](https://user-images.githubusercontent.com/64348163/80300108-5e190e80-87cc-11ea-8720-72189933d1d5.png)
[output_log.txt](https://github.com/miZyind/ONI-Mods/files/4534758/output_log.txt)

**Comment by miZyind** [comment]
感謝回報！你的圖片跟日誌看起來
目前你所用的翻譯包版本還是 v2020.4.24 版唷！沒有更新成功
因為 v2020.4.26 版，「過敏症」跟「嗜睡症」已經簡稱為「過敏」、「嗜睡」了
但是圖片中看起來這兩種負面特質還是三個字
新版會如下圖所示：
[image: v2020.4.26.jpg]

這個問題是因為缺氧的模組功能很不齊全，遊戲中看不到模組的版本
而有時候模組更新了，也不會自動下載 + 安裝新版
建議可以裝裝看 Mod Manager 模組，就能夠在遊戲的模組清單內看到版本
並手動按下更新，或是打開自動更新功能：
[image: image.png]

**Comment by miZyind** [comment]
感謝回報！你的圖片跟日誌看起來
目前你所用的翻譯包版本還是 v2020.4.24 版唷！沒有更新成功
因為 v2020.4.26 版，「過敏症」跟「嗜睡症」已經簡稱為「過敏」、「嗜睡」了
但是圖片中看起來這兩種負面特質還是三個字
新版會如下圖所示：
![image](https://user-images.githubusercontent.com/21041375/80426770-97f32d80-8910-11ea-8cae-240e3e7bdc5c.png)

這個問題是因為缺氧的模組功能很不齊全，遊戲中看不到模組的版本
而有時候模組更新了，也不會自動下載 + 安裝新版
建議可以裝裝看 Mod Manager 模組，就能夠在遊戲的模組清單內看到版本
並手動按下更新，或是打開自動更新功能：
![image](https://user-images.githubusercontent.com/21041375/80426777-9cb7e180-8910-11ea-89fc-2187e14a3905.png)

根據 2020.4.27 晚間的回報，更新後問題已解決，關閉此 Issue：
![image](https://user-images.githubusercontent.com/21041375/80426975-0b953a80-8911-11ea-827f-ca254d19d92f.png)
