### ISSUE TITLE
無法使用 ILRepack.Lib.MSBuild.Task 2.0.18.2 編譯

### ISSUE THREAD

**Issue by mn1712trungson** [miZyind/ONI-Mods#3]
MSB4064
The "OutputType" parameter is not supported by the "ILRepack" task loaded from assembly: ILRepack.Lib.MSBuild.Task, Version=2.0.18.2, Culture=neutral, PublicKeyToken=f7072046361f3979 from the path: C:\Users\mn1712\.nuget\packages\ilrepack.lib.msbuild.task\2.0.18.2\build\ILRepack.Lib.MSBuild.Task.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.

**Comment by miZyind** [comment]
Cảm ơn bạn báo cáo vấn đề này!
Tôi đã xử lý vấn đề của biên dịch.
Nhưng tôi không còn chơi game này nữa.
Nếu có vấn đề với việc sử dụng MOD, xin vui lòng tự nghiên cứu nha.
